@startuml
actor Usuario
actor Administrador

rectangle "Tocador de Música" {
    Usuario -- (Buscar Música)
    Usuario -- (Reproduzir Música)
    Usuario -- (Criar Playlist)
    Usuario -- (Adicionar Música à Playlist)
    Usuario -- (Remover Música da Playlist)
    Usuario -- (Explorar Playlists)
}

rectangle "Administração do Sistema" {
    Administrador -- (Atualizar Banco de Dados de Músicas)
}

@enduml
